vms:
- name: node1
  memory: 8192
  cpus: 4
  box: gutehall/ubuntu24-10
  disk: false
- name: node2
  memory: 8192
  cpus: 4
  box: gutehall/ubuntu24-10
  disk: false
- name: node3
  memory: 8192
  cpus: 4
  box: gutehall/ubuntu24-10
  disk: true
