apiVersion: v1
kind: ConfigMap
metadata:
  name: ctfd-config
  namespace: ctfd
  labels:
    app: ctfd
data:
  UPLOAD_FOLDER: /var/uploads
  DATABASE_URL: mysql+pymysql://ctfd:ctfd@ctfd-mariadb.ctfd.svc.cluster.local:3306/ctfd
  REDIS_URL: redis://ctfd-redis:6379
  WORKERS: "1"
  LOG_FOLDER: /var/log/CTFd
  REVERSE_PROXY: "True"
